/* =====================================================================================
   VIZITOR -> DIRECT SQL SERVER MIGRATION
   STEP 2 : LEAST-PRIVILEGE LOGIN TEMPLATE FOR THE ANDROID CLIENT

   *** TEMPLATE - NOT YET EXECUTABLE AS-IS ***
   The object list below MUST be filled from the output of 01_inventory_atiran2.sql
   (Sections 1, 9b and 11). Nothing here is guessed: do not run it before the
   inventory exists, otherwise you will either over-grant or break the app.

   RULES APPLIED
     - no sa, no db_owner, no sysadmin
     - SQL Server Authentication (as required by the brief), CHECK_POLICY = ON
     - password supplied as a sqlcmd variable -> never written in this file,
       never echoed to the output
     - SELECT-only by default; EXECUTE only on the specific posting procedures
       that the app really calls; INSERT/UPDATE only where the app really writes
     - explicit DENY on dangerous surface area

   HOW TO RUN (password prompted via variable, never in the transcript):
     sqlcmd -S <SQL_SERVER_IP>,1433 -d Atiran2 -U <admin_user> ^
            -v SqlLoginPassword="<paste strong password here, it is not stored in the script>" ^
            -i 02_least_privilege_login.sql -o grants-result.txt
   ===================================================================================== */

/* Run with sqlcmd: ":on error exit" makes the guard rail below abort the whole script
   instead of only the current batch. (In SSMS, enable SQLCMD mode.) */
:on error exit
SET NOCOUNT ON;
GO

/* ---------------------------------------------------------------------------
   0) Guard rails
   --------------------------------------------------------------------------- */
IF N'$(SqlLoginPassword)' = N'' OR N'$(SqlLoginPassword)' LIKE N'%paste strong%'
BEGIN
    RAISERROR('Aborted: pass the password with sqlcmd -v SqlLoginPassword="..." (do not edit this file).', 16, 1);
END
GO

/* ---------------------------------------------------------------------------
   1) Server login (dynamic SQL so the password never appears in this script)
   --------------------------------------------------------------------------- */
BEGIN TRY
    DECLARE @pwd  nvarchar(256) = N'$(SqlLoginPassword)';
    DECLARE @sql  nvarchar(max);

    IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'vizitor_app')
    BEGIN
        SET @sql = N'CREATE LOGIN [vizitor_app] WITH PASSWORD = N'''
                 + REPLACE(@pwd, '''', '''''')
                 + N''', CHECK_POLICY = ON, CHECK_EXPIRATION = OFF, DEFAULT_DATABASE = [Atiran2];';
        EXEC sp_executesql @sql;
        PRINT 'LOGIN [vizitor_app] created.';
    END
    ELSE
        PRINT 'LOGIN [vizitor_app] already exists - password NOT changed by this script.';

    SET @pwd = N'';   /* clear from memory as early as possible */
END TRY
BEGIN CATCH
    PRINT 'Login step failed: ' + ERROR_MESSAGE();
END CATCH
GO

/* ---------------------------------------------------------------------------
   2) Database user + application roles
   --------------------------------------------------------------------------- */
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'vizitor_app')
    CREATE USER [vizitor_app] FOR LOGIN [vizitor_app];
GO

IF DATABASE_PRINCIPAL_ID(N'vizitor_reader') IS NULL
    CREATE ROLE [vizitor_reader] AUTHORIZATION [dbo];
IF DATABASE_PRINCIPAL_ID(N'vizitor_writer') IS NULL
    CREATE ROLE [vizitor_writer] AUTHORIZATION [dbo];
GO

ALTER ROLE [vizitor_reader] ADD MEMBER [vizitor_app];
/* Add the writer role ONLY if the app really posts invoices/customers from the phone: */
-- ALTER ROLE [vizitor_writer] ADD MEMBER [vizitor_app];
GO

/* ---------------------------------------------------------------------------
   3) READ grants
      *** FILL FROM INVENTORY SECTION 1 / 9b ***
      Replace the placeholder names with the objects that actually exist and are
      actually used by Vizitor. Keep this list as short as possible.
   --------------------------------------------------------------------------- */

/* --- authentication / session layer --- */
GRANT SELECT ON OBJECT::[dbo].[sys_users]        TO [vizitor_reader];  -- verify columns first (Section 2)
GRANT SELECT ON OBJECT::[dbo].[Roles]            TO [vizitor_reader];
GRANT SELECT ON OBJECT::[dbo].[osystems]         TO [vizitor_reader];

/* --- visitor scope layer --- */
GRANT SELECT ON OBJECT::[dbo].[visitors]         TO [vizitor_reader];

/* --- customer layer --- */
GRANT SELECT ON OBJECT::[dbo].[CUSTOMERS]        TO [vizitor_reader];
GRANT SELECT ON OBJECT::[dbo].[custgroup]        TO [vizitor_reader];
GRANT SELECT ON OBJECT::[dbo].[CITYS]            TO [vizitor_reader];
-- GRANT SELECT ON OBJECT::[dbo].[sys_cus]       TO [vizitor_reader];  -- only if it exists
-- GRANT SELECT ON OBJECT::[dbo].[cust_act]      TO [vizitor_reader];  -- only if it exists

/* --- product / pricing / stock layer --- */
GRANT SELECT ON OBJECT::[dbo].[inventory]                 TO [vizitor_reader];
GRANT SELECT ON OBJECT::[dbo].[kagroup]                   TO [vizitor_reader];
GRANT SELECT ON OBJECT::[dbo].[forosh_price]              TO [vizitor_reader];
GRANT SELECT ON OBJECT::[dbo].[inventory_anbars]          TO [vizitor_reader];
GRANT SELECT ON OBJECT::[dbo].[Inventory_Anbars_Variety]  TO [vizitor_reader];

/* --- documents (read-back of proforma / orders) --- */
GRANT SELECT ON OBJECT::[dbo].[sailfact]         TO [vizitor_reader];
GRANT SELECT ON OBJECT::[dbo].[subsailfact]      TO [vizitor_reader];
-- GRANT SELECT ON OBJECT::[dbo].[subsailfact_pish] TO [vizitor_reader];  -- only if it is a TABLE
-- GRANT SELECT ON OBJECT::[dbo].[ka_act]           TO [vizitor_reader];
-- GRANT SELECT ON OBJECT::[dbo].[new_cust]         TO [vizitor_reader];

/* ---------------------------------------------------------------------------
   4) EXECUTE grants - ONLY the procedures the app must call
      *** FILL FROM INVENTORY SECTIONS 3, 4, 11 ***
      Never grant EXECUTE blindly: first read the definition and the parameter
      list, confirm the transaction behaviour, then grant.
   --------------------------------------------------------------------------- */
-- GRANT EXECUTE ON OBJECT::[dbo].[add_sail_pish]      TO [vizitor_writer];
-- GRANT EXECUTE ON OBJECT::[dbo].[AddInvoice]         TO [vizitor_writer];
-- GRANT EXECUTE ON OBJECT::[dbo].[FixMojodi]          TO [vizitor_writer];
-- GRANT EXECUTE ON OBJECT::[dbo].[fn_GetVisitorsByRoleId] TO [vizitor_reader]; -- function: needs SELECT, not EXECUTE

/* Table-valued / scalar functions are granted with SELECT: */
-- GRANT SELECT ON OBJECT::[dbo].[fn_GetVisitorsByRoleId] TO [vizitor_reader];

/* ---------------------------------------------------------------------------
   5) WRITE grants - only if the phone really inserts (e.g. new customer)
   --------------------------------------------------------------------------- */
-- GRANT INSERT ON OBJECT::[dbo].[CUSTOMERS]        TO [vizitor_writer];
-- GRANT INSERT ON OBJECT::[dbo].[subsailfact_pish] TO [vizitor_writer];
-- GRANT UPDATE ON OBJECT::[dbo].[inventory_anbars] TO [vizitor_writer];   -- avoid if a proc already does it

/* ---------------------------------------------------------------------------
   6) DENY the dangerous surface (defence in depth for a credential that lives
      inside a decompilable APK)

      Database-scope denies (safe to run here):
   --------------------------------------------------------------------------- */
BEGIN TRY
    /* Stops the app login from reading the bodies of procedures it does not own.
       Remove this line while you are still debugging, re-add it for production. */
    DENY VIEW DEFINITION TO [vizitor_app];
    /* No schema changes, ever. */
    DENY ALTER ON SCHEMA::[dbo] TO [vizitor_app];
    DENY CREATE TABLE     TO [vizitor_app];
    DENY CREATE VIEW      TO [vizitor_app];
    DENY CREATE PROCEDURE TO [vizitor_app];
    DENY CREATE FUNCTION  TO [vizitor_app];
    DENY CREATE TRIGGER   TO [vizitor_app];
    PRINT 'Database-scope DENY hardening applied.';
END TRY
BEGIN CATCH
    PRINT 'Some database-scope DENY statements were skipped: ' + ERROR_MESSAGE();
END CATCH
GO

/* ---------------------------------------------------------------------------
   6b) Server-scope denies - these objects live in [master], so run this block
       separately while connected to master (they are intentionally NOT executed
       here, because it would fail in the Atiran2 context):

         USE [master];
         GO
         DENY EXECUTE ON [xp_cmdshell]   TO [vizitor_app];
         DENY EXECUTE ON [xp_regread]    TO [vizitor_app];
         DENY EXECUTE ON [xp_regwrite]   TO [vizitor_app];
         DENY EXECUTE ON [sp_OACreate]   TO [vizitor_app];
         DENY EXECUTE ON [sp_OAMethod]   TO [vizitor_app];
         DENY EXECUTE ON [sp_addlogin]   TO [vizitor_app];
         DENY VIEW SERVER STATE           TO [vizitor_app];
         DENY VIEW ANY DATABASE           TO [vizitor_app];
         DENY ALTER ANY LOGIN             TO [vizitor_app];
         GO

       Also confirm the login is NOT a member of any server role:
         SELECT sp.name AS LoginName, sr.name AS ServerRole
         FROM sys.server_role_members m
         JOIN sys.server_principals sp ON sp.principal_id = m.member_principal_id
         JOIN sys.server_principals sr ON sr.principal_id = m.role_principal_id
         WHERE sp.name = 'vizitor_app';   -- expected: 0 rows
   --------------------------------------------------------------------------- */

/* ---------------------------------------------------------------------------
   7) Verification - run as the new login afterwards and confirm the app's
      real queries succeed and everything else fails
   --------------------------------------------------------------------------- */
PRINT '';
PRINT 'Grants now in place for vizitor_app:';
SELECT
    dp.name              AS Grantee,
    perm.permission_name AS Permission,
    perm.state_desc      AS State,
    SCHEMA_NAME(o.schema_id) + '.' + o.name AS OnObject
FROM sys.database_permissions perm
JOIN sys.database_principals dp ON dp.principal_id = perm.grantee_principal_id
LEFT JOIN sys.objects o         ON o.object_id = perm.major_id
WHERE dp.name IN ('vizitor_app','vizitor_reader','vizitor_writer')
ORDER BY OnObject, perm.permission_name;
GO

/* =====================================================================================
   SERVER / NETWORK CONFIGURATION (do these in SQL Server Configuration Manager +
   Windows Firewall - they cannot be expressed in T-SQL):

   1. SQL Server Network Configuration -> Protocols -> TCP/IP = Enabled
      -> IPAll: TCP Port = 1433, TCP Dynamic Ports = (empty)   [named instances otherwise
         use a dynamic port and the phone would need SQL Browser / UDP 1434]
   2. SQL Server Properties -> Security -> "SQL Server and Windows Authentication mode"
   3. SQL Server Properties -> Connections -> "Allow remote connections to this server"
   4. Force Encryption: SQL Server Network Configuration -> right-click Protocols ->
      Properties -> Force Encryption = Yes  (requires a valid certificate; strongly
      recommended - see the driver/TLS notes in the migration plan)
   5. Windows Firewall (inbound, restricted to the visitor subnet/VPN only):
         New-NetFirewallRule -DisplayName "SQL Server 1433 (Vizitor)" `
           -Direction Inbound -Protocol TCP -LocalPort 1433 -Action Allow `
           -RemoteAddress <VPN_or_LAN_subnet>      # never 0.0.0.0/0
         New-NetFirewallRule -DisplayName "SQL Browser UDP 1434" -Direction Inbound `
           -Protocol UDP -LocalPort 1434 -Action Allow -RemoteAddress <VPN_or_LAN_subnet>
      (Only needed for named instances; prefer a fixed TCP port and keep UDP closed.)
   ===================================================================================== */
